services:
  open-webui:
    image: markjnt/sapv-chatapp
    container_name: open-webui
    pull_policy: always
    volumes:
      - open-webui:/app/backend/data
    environment:
      - 'OLLAMA_BASE_URL=${OLLAMA_BASE_URL}'
      - 'WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}'
    env_file:
      - .env
    networks:
      - traefik-public
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.sapv-chatapp.rule=Host(`${WEB_DOMAIN}`)"
      - "traefik.http.routers.sapv-chatapp.entrypoints=websecure"
      - "traefik.http.routers.sapv-chatapp.tls.certresolver=letsencrypt"
      - "traefik.http.services.sapv-chatapp.loadbalancer.server.port=8080"
      - "traefik.http.services.sapv-chatapp.loadbalancer.server.scheme=http"

volumes:
  open-webui: {}

networks:
  traefik-public:
    external: true
    name: traefik-public
